decrypt:
  id_rsa: "repo/github-deploy.key.asc"
  id_rsa.pub: "repo/github-deploy.key.pub.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
install: |-
  java -version
deploy:
  script: |
    mkdir -p ~/.ssh
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    mv -v ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    git remote -v
    git config --list
    ls -la ~/.ssh/
    date --iso-8601=seconds > rultor.log
    git add rultor.log
    git commit -m 'Commit by Rultor'
    gpg --list-keys --quiet
    cp ../pubring.gpg ../secring.gpg ${HOME}/.gnupg
    gpg --list-keys
    echo "no-use-agent" >> ${HOME}/.gnupg/gpg.conf
    echo "batch" >> ${HOME}/.gnupg/gpg.conf
    echo "no-tty" >> ${HOME}/.gnupg/gpg.conf
    echo "passphrase ${gpg_pass}" >> ${HOME}/.gnupg/gpg.conf
    git tag --local-user='valery1707@gmail.com' -m "Signed tag" v$(date '+%Y%m%dT%H%M%S')
    git push --all origin
    git push --tags origin
