decrypt:
  id_rsa: "repo/github-deploy.key.asc"
  id_rsa.pub: "repo/github-deploy.key.pub.asc"
install: |-
  java -version
deploy:
  script: |
    mkdir -p ~/.ssh
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    mv -v ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    git remote -v
    git config --list
    ls -la ~/.ssh/
    date --iso-8601=seconds > rultor.log
    git add rultor.log
    git commit -m 'Commit by Rultor'
    git push --all origin
